START_LISTENING_MESSAGE_TO_SERVER = 'start_listening'
QUESTION_MESSAGE_TO_CLIENT = 'question'
ANSWER_QUERY_MESSAGE_TO_SERVER = 'answer_action'
ANSWER_MESSAGE_TO_CLIENT = 'answer'
STOP_ANSWER_MESSAGE_TO_CLIENT = 'stop_answer'

QUESTIONS_CACHE_SIZE = 30