START_LISTENING_MESSAGE_TO_SERVER = 'start_listening'
QUESTION_MESSAGE_TO_CLIENT = 'question'
ANSWER_QUERY_MESSAGE_TO_SERVER = 'answer_action'
ANSWER_MESSAGE_TO_CLIENT = 'answer'
STOP_ANSWER_MESSAGE_TO_CLIENT = 'stop_answer'
CORRECT_ANSWER_MESSAGE_TO_CLIENT = 'correct_answer'
INCORRECT_ANSWER_MESSAGE_TO_CLIENT = 'wrong_answer'
INCORRECT_ANSWER_ANOTHER_PLAYER_MESSAGE_TO_CLIENT = 'wrong_answer_another_player'
PLAYER_ANSWER_MESSAGE_TO_SERVER = 'player_answer'
SCORES_CHANGED_MESSAGE_TO_CLIENT = 'scores_changed'

QUESTIONS_CACHE_SIZE = 30

NAME_COOKIE = 'name_cookie'